### PR TITLE
Fixes `main` file

### PR DESCRIPTION
**Pull request by deiga**

### CODE REVIEW

**Comment by gkatsev** [comment]
This project is set up to be used with a bundler by default. Changing the main file away from that breaks what bundlers expect and also how we build out the dist file for users who don't use bundlers. This is also why the tests are failing.

**Comment by deiga** [comment]
@gkatsev Fair enough. I understand the reasoning, but currently the folder `es5` doesn't exist and thus the main fail is erronneous.

**Comment by gkatsev** [comment]
When I run `npm install` I see the `es5` directory there. It's a built directory so we don't check it in.

**Comment by deiga** [comment]
Sure, but the `main` file can't be in a generated directory as that kind of breaks contract as a package

**Comment by gkatsev** [comment]
Sure it can. Nothing about the git repo requires it to work out of the box after cloning. It's available correctly on npm. If you're cloning the repo make sure to run `npm run build` after.

**Pull request closed without merging**
