### PR TITLE
feat: Choose placement of overlay elements in controlBar

### PR DESCRIPTION
**Pull request by bc-paul**
Summary:
Choose where the overlay element(s) should be placed when attached to the control bar.

Issue:
The current overlay placement does not allow user interaction with menu items when an overlay is present in the same display area as the menu. 

Use case example:
You want to attach an overlay to the bottom right hand side, and have captions present.

Proposed solution:
If attachToControlBar is true, and overlays are configured with an align of "bottom", "bottom-left", or "bottom-right", attach the overlays to either the insertBefore component, or as the first child of the control bar. Otherwise, attach the overlays before the control bar. If no controls are present, attach the overlays as a child of the player.

### CODE REVIEW

**Comment by BrandonOCasey** [comment]
Ok the tests pass locally, If you want you can bump the version of `rollup` in `package.json` to `^0.51.8`. That will get them to pass on Travis.

**Comment by BrandonOCasey** [comment]
Also, thanks for the PR this look great other than my comments about the option change!

**Comment by gkatsev** [comment]
Heh, I was about to suggest that mixing types in options isn't a great idea. I know we've done it before but not sure I want to keep doing it. I don't have strong feelings on this right now for this plugin, at least.

**Comment by ishita12** [comment]
QA LGTM

**Pull request merged**
